export const PT_GROUPS = ["Greater Lisbon", "Greater Porto", "Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra", "Faro", "Guarda", "Leiria", "Lisboa", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu", "Évora", "Madeira", "Azores"]

const m = (label, group, district, keywords = '') => ({ value: label, label, group, district, keywords: `${district} ${keywords}`.trim() })

export const PT_MUNICIPALITIES = [
    m("Lisbon", "Greater Lisbon", "Lisboa", "lisboa"),
    m("Alcochete", "Greater Lisbon", "Setúbal"),
    m("Almada", "Greater Lisbon", "Setúbal"),
    m("Amadora", "Greater Lisbon", "Lisboa"),
    m("Barreiro", "Greater Lisbon", "Setúbal"),
    m("Cascais", "Greater Lisbon", "Lisboa"),
    m("Loures", "Greater Lisbon", "Lisboa"),
    m("Mafra", "Greater Lisbon", "Lisboa"),
    m("Moita", "Greater Lisbon", "Setúbal"),
    m("Montijo", "Greater Lisbon", "Setúbal"),
    m("Odivelas", "Greater Lisbon", "Lisboa"),
    m("Oeiras", "Greater Lisbon", "Lisboa"),
    m("Palmela", "Greater Lisbon", "Setúbal"),
    m("Seixal", "Greater Lisbon", "Setúbal"),
    m("Sesimbra", "Greater Lisbon", "Setúbal"),
    m("Setúbal", "Greater Lisbon", "Setúbal"),
    m("Sintra", "Greater Lisbon", "Lisboa"),
    m("Vila Franca de Xira", "Greater Lisbon", "Lisboa"),
    m("Arouca", "Greater Porto", "Aveiro"),
    m("Espinho", "Greater Porto", "Aveiro"),
    m("Gondomar", "Greater Porto", "Porto"),
    m("Maia", "Greater Porto", "Porto"),
    m("Matosinhos", "Greater Porto", "Porto"),
    m("Oliveira de Azeméis", "Greater Porto", "Aveiro"),
    m("Paredes", "Greater Porto", "Porto"),
    m("Porto", "Greater Porto", "Porto"),
    m("Póvoa de Varzim", "Greater Porto", "Porto"),
    m("Santa Maria da Feira", "Greater Porto", "Aveiro"),
    m("Santo Tirso", "Greater Porto", "Porto"),
    m("São João da Madeira", "Greater Porto", "Aveiro"),
    m("Trofa", "Greater Porto", "Porto"),
    m("Vale de Cambra", "Greater Porto", "Aveiro"),
    m("Valongo", "Greater Porto", "Porto"),
    m("Vila Nova de Gaia", "Greater Porto", "Porto"),
    m("Vila do Conde", "Greater Porto", "Porto"),
    m("Albergaria-a-Velha", "Aveiro", "Aveiro"),
    m("Anadia", "Aveiro", "Aveiro"),
    m("Aveiro", "Aveiro", "Aveiro"),
    m("Castelo de Paiva", "Aveiro", "Aveiro"),
    m("Estarreja", "Aveiro", "Aveiro"),
    m("Mealhada", "Aveiro", "Aveiro"),
    m("Murtosa", "Aveiro", "Aveiro"),
    m("Oliveira do Bairro", "Aveiro", "Aveiro"),
    m("Ovar", "Aveiro", "Aveiro"),
    m("Sever do Vouga", "Aveiro", "Aveiro"),
    m("Vagos", "Aveiro", "Aveiro"),
    m("Águeda", "Aveiro", "Aveiro"),
    m("Ílhavo", "Aveiro", "Aveiro"),
    m("Aljustrel", "Beja", "Beja"),
    m("Almodôvar", "Beja", "Beja"),
    m("Alvito", "Beja", "Beja"),
    m("Barrancos", "Beja", "Beja"),
    m("Beja", "Beja", "Beja"),
    m("Castro Verde", "Beja", "Beja"),
    m("Cuba", "Beja", "Beja"),
    m("Ferreira do Alentejo", "Beja", "Beja"),
    m("Moura", "Beja", "Beja"),
    m("Mértola", "Beja", "Beja"),
    m("Odemira", "Beja", "Beja"),
    m("Ourique", "Beja", "Beja"),
    m("Serpa", "Beja", "Beja"),
    m("Vidigueira", "Beja", "Beja"),
    m("Amares", "Braga", "Braga"),
    m("Barcelos", "Braga", "Braga"),
    m("Braga", "Braga", "Braga"),
    m("Cabeceiras de Basto", "Braga", "Braga"),
    m("Celorico de Basto", "Braga", "Braga"),
    m("Esposende", "Braga", "Braga"),
    m("Fafe", "Braga", "Braga"),
    m("Guimarães", "Braga", "Braga"),
    m("Póvoa de Lanhoso", "Braga", "Braga"),
    m("Terras de Bouro", "Braga", "Braga"),
    m("Vieira do Minho", "Braga", "Braga"),
    m("Vila Nova de Famalicão", "Braga", "Braga"),
    m("Vila Verde", "Braga", "Braga"),
    m("Vizela", "Braga", "Braga"),
    m("Alfândega da Fé", "Bragança", "Bragança"),
    m("Bragança", "Bragança", "Bragança"),
    m("Carrazeda de Ansiães", "Bragança", "Bragança"),
    m("Freixo de Espada à Cinta", "Bragança", "Bragança"),
    m("Macedo de Cavaleiros", "Bragança", "Bragança"),
    m("Miranda do Douro", "Bragança", "Bragança"),
    m("Mirandela", "Bragança", "Bragança"),
    m("Mogadouro", "Bragança", "Bragança"),
    m("Torre de Moncorvo", "Bragança", "Bragança"),
    m("Vila Flor", "Bragança", "Bragança"),
    m("Vimioso", "Bragança", "Bragança"),
    m("Vinhais", "Bragança", "Bragança"),
    m("Belmonte", "Castelo Branco", "Castelo Branco"),
    m("Castelo Branco", "Castelo Branco", "Castelo Branco"),
    m("Covilhã", "Castelo Branco", "Castelo Branco"),
    m("Fundão", "Castelo Branco", "Castelo Branco"),
    m("Idanha-a-Nova", "Castelo Branco", "Castelo Branco"),
    m("Oleiros", "Castelo Branco", "Castelo Branco"),
    m("Penamacor", "Castelo Branco", "Castelo Branco"),
    m("Proença-a-Nova", "Castelo Branco", "Castelo Branco"),
    m("Sertã", "Castelo Branco", "Castelo Branco"),
    m("Vila Velha de Ródão", "Castelo Branco", "Castelo Branco"),
    m("Vila de Rei", "Castelo Branco", "Castelo Branco"),
    m("Arganil", "Coimbra", "Coimbra"),
    m("Cantanhede", "Coimbra", "Coimbra"),
    m("Coimbra", "Coimbra", "Coimbra"),
    m("Condeixa-a-Nova", "Coimbra", "Coimbra"),
    m("Figueira da Foz", "Coimbra", "Coimbra"),
    m("Góis", "Coimbra", "Coimbra"),
    m("Lousã", "Coimbra", "Coimbra"),
    m("Mira", "Coimbra", "Coimbra"),
    m("Miranda do Corvo", "Coimbra", "Coimbra"),
    m("Montemor-o-Velho", "Coimbra", "Coimbra"),
    m("Oliveira do Hospital", "Coimbra", "Coimbra"),
    m("Pampilhosa da Serra", "Coimbra", "Coimbra"),
    m("Penacova", "Coimbra", "Coimbra"),
    m("Penela", "Coimbra", "Coimbra"),
    m("Soure", "Coimbra", "Coimbra"),
    m("Tábua", "Coimbra", "Coimbra"),
    m("Vila Nova de Poiares", "Coimbra", "Coimbra"),
    m("Albufeira", "Faro", "Faro"),
    m("Alcoutim", "Faro", "Faro"),
    m("Aljezur", "Faro", "Faro"),
    m("Castro Marim", "Faro", "Faro"),
    m("Faro", "Faro", "Faro"),
    m("Lagoa", "Faro", "Faro"),
    m("Lagos", "Faro", "Faro"),
    m("Loulé", "Faro", "Faro"),
    m("Monchique", "Faro", "Faro"),
    m("Olhão", "Faro", "Faro"),
    m("Portimão", "Faro", "Faro"),
    m("Silves", "Faro", "Faro"),
    m("São Brás de Alportel", "Faro", "Faro"),
    m("Tavira", "Faro", "Faro"),
    m("Vila Real de Santo António", "Faro", "Faro"),
    m("Vila do Bispo", "Faro", "Faro"),
    m("Aguiar da Beira", "Guarda", "Guarda"),
    m("Almeida", "Guarda", "Guarda"),
    m("Celorico da Beira", "Guarda", "Guarda"),
    m("Figueira de Castelo Rodrigo", "Guarda", "Guarda"),
    m("Fornos de Algodres", "Guarda", "Guarda"),
    m("Gouveia", "Guarda", "Guarda"),
    m("Guarda", "Guarda", "Guarda"),
    m("Manteigas", "Guarda", "Guarda"),
    m("Mêda", "Guarda", "Guarda"),
    m("Pinhel", "Guarda", "Guarda"),
    m("Sabugal", "Guarda", "Guarda"),
    m("Seia", "Guarda", "Guarda"),
    m("Trancoso", "Guarda", "Guarda"),
    m("Vila Nova de Foz Côa", "Guarda", "Guarda"),
    m("Alcobaça", "Leiria", "Leiria"),
    m("Alvaiázere", "Leiria", "Leiria"),
    m("Ansião", "Leiria", "Leiria"),
    m("Batalha", "Leiria", "Leiria"),
    m("Bombarral", "Leiria", "Leiria"),
    m("Caldas da Rainha", "Leiria", "Leiria"),
    m("Castanheira de Pêra", "Leiria", "Leiria"),
    m("Figueiró dos Vinhos", "Leiria", "Leiria"),
    m("Leiria", "Leiria", "Leiria"),
    m("Marinha Grande", "Leiria", "Leiria"),
    m("Nazaré", "Leiria", "Leiria"),
    m("Pedrógão Grande", "Leiria", "Leiria"),
    m("Peniche", "Leiria", "Leiria"),
    m("Pombal", "Leiria", "Leiria"),
    m("Porto de Mós", "Leiria", "Leiria"),
    m("Óbidos", "Leiria", "Leiria"),
    m("Alenquer", "Lisboa", "Lisboa"),
    m("Arruda dos Vinhos", "Lisboa", "Lisboa"),
    m("Azambuja", "Lisboa", "Lisboa"),
    m("Cadaval", "Lisboa", "Lisboa"),
    m("Lourinhã", "Lisboa", "Lisboa"),
    m("Sobral de Monte Agraço", "Lisboa", "Lisboa"),
    m("Torres Vedras", "Lisboa", "Lisboa"),
    m("Alter do Chão", "Portalegre", "Portalegre"),
    m("Arronches", "Portalegre", "Portalegre"),
    m("Avis", "Portalegre", "Portalegre"),
    m("Campo Maior", "Portalegre", "Portalegre"),
    m("Castelo de Vide", "Portalegre", "Portalegre"),
    m("Crato", "Portalegre", "Portalegre"),
    m("Elvas", "Portalegre", "Portalegre"),
    m("Fronteira", "Portalegre", "Portalegre"),
    m("Gavião", "Portalegre", "Portalegre"),
    m("Marvão", "Portalegre", "Portalegre"),
    m("Monforte", "Portalegre", "Portalegre"),
    m("Nisa", "Portalegre", "Portalegre"),
    m("Ponte de Sor", "Portalegre", "Portalegre"),
    m("Portalegre", "Portalegre", "Portalegre"),
    m("Sousel", "Portalegre", "Portalegre"),
    m("Amarante", "Porto", "Porto"),
    m("Baião", "Porto", "Porto"),
    m("Felgueiras", "Porto", "Porto"),
    m("Lousada", "Porto", "Porto"),
    m("Marco de Canaveses", "Porto", "Porto"),
    m("Paços de Ferreira", "Porto", "Porto"),
    m("Penafiel", "Porto", "Porto"),
    m("Abrantes", "Santarém", "Santarém"),
    m("Alcanena", "Santarém", "Santarém"),
    m("Almeirim", "Santarém", "Santarém"),
    m("Alpiarça", "Santarém", "Santarém"),
    m("Benavente", "Santarém", "Santarém"),
    m("Cartaxo", "Santarém", "Santarém"),
    m("Chamusca", "Santarém", "Santarém"),
    m("Constância", "Santarém", "Santarém"),
    m("Coruche", "Santarém", "Santarém"),
    m("Entroncamento", "Santarém", "Santarém"),
    m("Ferreira do Zêzere", "Santarém", "Santarém"),
    m("Golegã", "Santarém", "Santarém"),
    m("Mação", "Santarém", "Santarém"),
    m("Ourém", "Santarém", "Santarém"),
    m("Rio Maior", "Santarém", "Santarém"),
    m("Salvaterra de Magos", "Santarém", "Santarém"),
    m("Santarém", "Santarém", "Santarém"),
    m("Sardoal", "Santarém", "Santarém"),
    m("Tomar", "Santarém", "Santarém"),
    m("Torres Novas", "Santarém", "Santarém"),
    m("Vila Nova da Barquinha", "Santarém", "Santarém"),
    m("Alcácer do Sal", "Setúbal", "Setúbal"),
    m("Grândola", "Setúbal", "Setúbal"),
    m("Santiago do Cacém", "Setúbal", "Setúbal"),
    m("Sines", "Setúbal", "Setúbal"),
    m("Arcos de Valdevez", "Viana do Castelo", "Viana do Castelo"),
    m("Caminha", "Viana do Castelo", "Viana do Castelo"),
    m("Melgaço", "Viana do Castelo", "Viana do Castelo"),
    m("Monção", "Viana do Castelo", "Viana do Castelo"),
    m("Paredes de Coura", "Viana do Castelo", "Viana do Castelo"),
    m("Ponte da Barca", "Viana do Castelo", "Viana do Castelo"),
    m("Ponte de Lima", "Viana do Castelo", "Viana do Castelo"),
    m("Valença", "Viana do Castelo", "Viana do Castelo"),
    m("Viana do Castelo", "Viana do Castelo", "Viana do Castelo"),
    m("Vila Nova de Cerveira", "Viana do Castelo", "Viana do Castelo"),
    m("Alijó", "Vila Real", "Vila Real"),
    m("Boticas", "Vila Real", "Vila Real"),
    m("Chaves", "Vila Real", "Vila Real"),
    m("Mesão Frio", "Vila Real", "Vila Real"),
    m("Mondim de Basto", "Vila Real", "Vila Real"),
    m("Montalegre", "Vila Real", "Vila Real"),
    m("Murça", "Vila Real", "Vila Real"),
    m("Peso da Régua", "Vila Real", "Vila Real"),
    m("Ribeira de Pena", "Vila Real", "Vila Real"),
    m("Sabrosa", "Vila Real", "Vila Real"),
    m("Santa Marta de Penaguião", "Vila Real", "Vila Real"),
    m("Valpaços", "Vila Real", "Vila Real"),
    m("Vila Pouca de Aguiar", "Vila Real", "Vila Real"),
    m("Vila Real", "Vila Real", "Vila Real"),
    m("Armamar", "Viseu", "Viseu"),
    m("Carregal do Sal", "Viseu", "Viseu"),
    m("Castro Daire", "Viseu", "Viseu"),
    m("Cinfães", "Viseu", "Viseu"),
    m("Lamego", "Viseu", "Viseu"),
    m("Mangualde", "Viseu", "Viseu"),
    m("Moimenta da Beira", "Viseu", "Viseu"),
    m("Mortágua", "Viseu", "Viseu"),
    m("Nelas", "Viseu", "Viseu"),
    m("Oliveira de Frades", "Viseu", "Viseu"),
    m("Penalva do Castelo", "Viseu", "Viseu"),
    m("Penedono", "Viseu", "Viseu"),
    m("Resende", "Viseu", "Viseu"),
    m("Santa Comba Dão", "Viseu", "Viseu"),
    m("Sernancelhe", "Viseu", "Viseu"),
    m("Sátão", "Viseu", "Viseu"),
    m("São João da Pesqueira", "Viseu", "Viseu"),
    m("São Pedro do Sul", "Viseu", "Viseu"),
    m("Tabuaço", "Viseu", "Viseu"),
    m("Tarouca", "Viseu", "Viseu"),
    m("Tondela", "Viseu", "Viseu"),
    m("Vila Nova de Paiva", "Viseu", "Viseu"),
    m("Viseu", "Viseu", "Viseu"),
    m("Vouzela", "Viseu", "Viseu"),
    m("Alandroal", "Évora", "Évora"),
    m("Arraiolos", "Évora", "Évora"),
    m("Borba", "Évora", "Évora"),
    m("Estremoz", "Évora", "Évora"),
    m("Montemor-o-Novo", "Évora", "Évora"),
    m("Mora", "Évora", "Évora"),
    m("Mourão", "Évora", "Évora"),
    m("Portel", "Évora", "Évora"),
    m("Redondo", "Évora", "Évora"),
    m("Reguengos de Monsaraz", "Évora", "Évora"),
    m("Vendas Novas", "Évora", "Évora"),
    m("Viana do Alentejo", "Évora", "Évora"),
    m("Vila Viçosa", "Évora", "Évora"),
    m("Évora", "Évora", "Évora"),
    m("Calheta", "Madeira", "Madeira"),
    m("Câmara de Lobos", "Madeira", "Madeira"),
    m("Funchal", "Madeira", "Madeira"),
    m("Machico", "Madeira", "Madeira"),
    m("Ponta do Sol", "Madeira", "Madeira"),
    m("Porto Moniz", "Madeira", "Madeira"),
    m("Porto Santo", "Madeira", "Madeira"),
    m("Ribeira Brava", "Madeira", "Madeira"),
    m("Santa Cruz", "Madeira", "Madeira"),
    m("Santana", "Madeira", "Madeira"),
    m("São Vicente", "Madeira", "Madeira"),
    m("Angra do Heroísmo", "Azores", "Azores"),
    m("Calheta (São Jorge)", "Azores", "Azores"),
    m("Corvo", "Azores", "Azores"),
    m("Horta", "Azores", "Azores"),
    m("Lagoa (Azores)", "Azores", "Azores"),
    m("Lajes das Flores", "Azores", "Azores"),
    m("Lajes do Pico", "Azores", "Azores"),
    m("Madalena", "Azores", "Azores"),
    m("Nordeste", "Azores", "Azores"),
    m("Ponta Delgada", "Azores", "Azores"),
    m("Povoação", "Azores", "Azores"),
    m("Praia da Vitória", "Azores", "Azores"),
    m("Ribeira Grande", "Azores", "Azores"),
    m("Santa Cruz da Graciosa", "Azores", "Azores"),
    m("Santa Cruz das Flores", "Azores", "Azores"),
    m("São Roque do Pico", "Azores", "Azores"),
    m("Velas", "Azores", "Azores"),
    m("Vila Franca do Campo", "Azores", "Azores"),
    m("Vila do Porto", "Azores", "Azores"),
]

export const GREATER_LISBON = new Set(PT_MUNICIPALITIES.filter((c) => c.group === 'Greater Lisbon').map((c) => c.value))

const ZONES = { Madeira: 'Atlantic/Madeira', Azores: 'Atlantic/Azores' }

export const NG_CITIES = [
    'Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Kano', 'Benin City', 'Enugu', 'Abeokuta', 'Kaduna', 'Jos',
    'Ilorin', 'Owerri', 'Uyo', 'Calabar', 'Warri', 'Asaba', 'Onitsha', 'Akure', 'Osogbo', 'Aba',
].map((city) => ({ value: city, label: city }))

export const POPULAR_COUNTRIES = ['PT', 'NG', 'BR', 'GB', 'ES', 'FR', 'US', 'AO', 'CV']

const deviceZone = () => {
    try { return Intl.DateTimeFormat().resolvedOptions().timeZone || 'Europe/Lisbon' } catch { return 'Europe/Lisbon' }
}

export const timezoneForPlace = (country, city) => {
    if (country === 'PT') return ZONES[PT_MUNICIPALITIES.find((c) => c.value === city)?.district] || 'Europe/Lisbon'
    if (country === 'NG') return 'Africa/Lagos'
    return deviceZone()
}

export const inLaunchArea = (country, city) => country === 'PT' && GREATER_LISBON.has(city)
