// Mirrors the businesses_slug_rules constraint in Supabase. Change both together.
export const RESERVED_SLUGS = new Set([
    'about',
    'account',
    'admin',
    'api',
    'app',
    'assets',
    'auth',
    'blog',
    'book',
    'booking',
    'bookings',
    'businesses',
    'careers',
    'client',
    'clients',
    'contact',
    'cookies',
    'dashboard',
    'discover',
    'docs',
    'download',
    'dpa',
    'edit',
    'faq',
    'forgot-password',
    'help',
    'home',
    'legal',
    'login',
    'logout',
    'me',
    'new',
    'notice',
    'null',
    'partner',
    'partners',
    'partnership',
    'portal',
    'press',
    'pricing',
    'privacy',
    'ranking',
    'register',
    'reset-password',
    'search',
    'settings',
    'signin',
    'signup',
    'static',
    'status',
    'subprocessors',
    'support',
    'terms',
    'undefined',
    'waitlist',
    'www',
])

export const SLUG_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/

export const slugProblem = (slug) => {
    if (slug.length < 3 || slug.length > 60) return 'Business URL must be 3 to 60 characters.'
    if (!SLUG_PATTERN.test(slug)) return 'Use lowercase letters, numbers and single hyphens only.'
    if (RESERVED_SLUGS.has(slug)) return 'That URL is reserved. Try adding your area, like femtos-baixa.'
    return null
}
