export default async ({ browser, url, check, cover }) => {
    const wait = (ms = 250) => new Promise((r) => setTimeout(r, ms))
    const open = async (path, vw = 1272, vh = 588, touch = false) => {
      const page = await browser.newPage()
      page.errors = []
      page.on('pageerror', (e) => page.errors.push(e.message))
      await page.setViewport({ width: vw, height: vh, hasTouch: touch, isMobile: touch })
      await page.goto(`${url}/?path=${encodeURIComponent(path)}`, { waitUntil: 'networkidle0' })
      await wait(500)
      return page
    }
    const updates = (p) => p.evaluate(() => window.__calls.filter((c) => c[0] === 'update' && c[1] === 'businesses').map((c) => c[2]))
    const save = (p) => p.evaluate(() => document.querySelector('.biz-bp__save')?.textContent)
    const field = async (p, label) => p.evaluateHandle((label) => {
      const l = [...document.querySelectorAll('.ui-field__label')].find((e) => e.firstChild.textContent.trim() === label)
      return document.getElementById(l.htmlFor)
    }, label)
    const typeInto = async (p, label, text, clear = true) => {
      const el = await field(p, label)
      await el.focus()
      if (clear) { await p.keyboard.down('Control'); await p.keyboard.press('a'); await p.keyboard.up('Control'); await p.keyboard.press('Backspace') }
      if (text) await p.keyboard.type(text)
    }

    let p = await open('/portal/page')
    await wait(1200)
    check((await updates(p)).length === 0, `no save on open: ${JSON.stringify(await updates(p))}`)
    check(await save(p) === 'Changes save as you go', `idle text ${await save(p)}`)
    check(await p.evaluate(() => Boolean(document.querySelector('.biz-bp__preview .lc-pub'))), 'wide preview shown at 1272')
    const ph = await p.evaluate(() => { const r = document.querySelector('.biz-bp__preview .ui-phone').getBoundingClientRect(); return { top: r.top, bottom: r.bottom, vh: innerHeight } })
    check(ph.top >= 0 && ph.bottom <= ph.vh, `phone fully visible ${JSON.stringify(ph)}`)

    await typeInto(p, 'Description', 'Skin fades and hot towel shaves in Arroios.')
    check(await save(p) !== 'Saving' || true, 'typing')
    await wait(1100)
    let u = await updates(p)
    check(u.length === 1 && u[0].description === 'Skin fades and hot towel shaves in Arroios.' && Object.keys(u[0]).length === 1, `description saved alone ${JSON.stringify(u)}`)
    check(await save(p) === 'All changes saved', `saved text ${await save(p)}`)
    check(await p.evaluate(() => document.querySelector('.biz-bp__preview .lc-pub__about')?.textContent) === 'Skin fades and hot towel shaves in Arroios.', 'preview shows description')

    await typeInto(p, 'Business name', '')
    await wait(1000)
    check(await p.evaluate(() => document.body.textContent.includes('Enter the name clients know you by')), 'empty name error')
    check(await save(p) === 'Fix the highlighted field to save it', `blocked text ${await save(p)}`)
    check((await updates(p)).length === 1, 'empty name not saved')
    await p.keyboard.type('Femtos Barbearia Arroios')
    await wait(1100)
    u = await updates(p)
    check(u.length === 2 && u[1].business_name === 'Femtos Barbearia Arroios', `name saved ${JSON.stringify(u[1])}`)
    check(!('slug' in u[1]), 'name change never touches the address')
    check(await p.evaluate(() => document.querySelector('.biz-bizcard strong').textContent) === 'Femtos Barbearia Arroios', 'sidebar card shows new name')
    check(await p.evaluate(() => window.__refreshed > 0), 'profile refreshed after rename')

    await p.evaluate(() => [...document.querySelectorAll('.biz-bp__link [role=switch]')][0].click())
    await wait(600)
    u = await updates(p)
    check(u[u.length - 1].is_active === false, 'pause saved')
    check(await p.evaluate(() => document.querySelector('.biz-bp__link .ui-status').textContent) === 'Paused', 'status Paused')
    check(await p.evaluate(() => document.querySelector('.biz-bizcard small').textContent) === 'Bookings paused', 'sidebar shows paused')
    await p.evaluate(() => [...document.querySelectorAll('.biz-bp__link [role=switch]')][0].click())
    await wait(600)
    check((await updates(p)).slice(-1)[0].is_active === true, 'resume saved')

    await p.evaluate(() => [...document.querySelectorAll('.biz-bp__link button')].find((b) => b.textContent === 'Change').click())
    await wait(400)
    check(await p.evaluate(() => Boolean(document.querySelector('.biz-bp__warn'))), 'address sheet warns')
    const slugInput = await p.$('.biz-bp__slugsheet input')
    await slugInput.focus(); await p.keyboard.down('Control'); await p.keyboard.press('a'); await p.keyboard.up('Control'); await p.keyboard.press('Backspace'); await p.keyboard.type('taken-one'); await wait(800)
    check(await p.evaluate(() => document.querySelector('.biz-bp__slugstatus').textContent.startsWith('Taken')), 'taken shown')
    check(await p.evaluate(() => [...document.querySelectorAll('.ui-sheet button')].find((b) => b.textContent.includes('Change address')).disabled), 'cannot save taken')
    await slugInput.focus(); await p.keyboard.down('Control'); await p.keyboard.press('a'); await p.keyboard.up('Control'); await p.keyboard.press('Backspace'); await p.keyboard.type('Femtos Arroios!'); await wait(800)
    check(await p.evaluate(() => document.querySelector('.biz-bp__slugsheet input').value) === 'femtosarroios', 'address input cleans characters')
    await slugInput.focus(); await p.keyboard.down('Control'); await p.keyboard.press('a'); await p.keyboard.up('Control'); await p.keyboard.press('Backspace'); await p.keyboard.type('femtos-arroios'); await wait(800)
    check(await p.evaluate(() => document.querySelector('.biz-bp__slugstatus').textContent.startsWith('Available')), 'available shown')
    await p.evaluate(() => [...document.querySelectorAll('.ui-sheet button')].find((b) => b.textContent.includes('Change address')).click())
    await wait(700)
    check((await updates(p)).slice(-1)[0].slug === 'femtos-arroios', 'slug saved')
    check(await p.evaluate(() => document.querySelector('.biz-bp__slug').textContent) === 'femtos-arroios', 'link shows new address')
    check(await p.evaluate(() => !document.querySelector('.biz-bp__slugsheet')), 'sheet closed')

    check(await p.evaluate(() => document.querySelector('.biz-startrow__pct')?.textContent) === '88%', 'still 88% before logo')
    const input = await p.$('.ui-picker--logo input[type=file]')
    await input.uploadFile(cover)
    await wait(1500)
    check(await p.evaluate(() => window.__calls.some((c) => c[0] === 'upload' && /^b1\/logo-\d+\.(webp|jpg)$/.test(c[1]))), 'logo uploaded to business folder')
    check((await updates(p)).slice(-1)[0].logo_url?.includes('/brand/'), 'logo url saved')
    check(await p.evaluate(() => Boolean(document.querySelector('.ui-picker--logo .ui-picker__img'))), 'logo shows')
    check(await p.evaluate(() => Boolean(document.querySelector('.biz-bp__preview .lc-pub__logo img'))), 'preview shows logo')
    check(await p.evaluate(() => !document.querySelector('.biz-startrow')), 'getting started gone at 100%')

    await p.evaluate(() => [...document.querySelectorAll('#contact [role=switch]')][0].click())
    await wait(1100)
    check((await updates(p)).slice(-1)[0].whatsapp === null, 'whatsapp off saved')
    check(await p.evaluate(() => !document.querySelector('.biz-bp__preview .lc-pub__actions')?.textContent.includes('WhatsApp')), 'preview drops WhatsApp')
    await p.evaluate(() => [...document.querySelectorAll('#contact [role=switch]')][0].click())
    await wait(1100)
    check((await updates(p)).slice(-1)[0].whatsapp === '+351912345678', 'whatsapp on uses the business phone')
    check(await p.evaluate(() => document.querySelector('#contact .ui-switchrow__desc').textContent.includes('912 345 678')), 'switch names the number')
    check(await p.evaluate(() => !document.querySelector('#contact .ui-phone-field + .ui-phone-field') && document.querySelectorAll('#contact .ui-phone-field').length === 1), 'one number field when same')
    await p.evaluate(() => [...document.querySelectorAll('#contact button')].find((b) => b.textContent === 'Use another number').click())
    await wait(300)
    check(await p.evaluate(() => document.querySelectorAll('#contact .ui-phone-field').length === 2), 'second field for another number')
    await typeInto(p, 'WhatsApp number', '936 555 222')
    await wait(1100)
    check((await updates(p)).slice(-1)[0].whatsapp === '+351936555222', 'separate whatsapp saved')
    await p.evaluate(() => [...document.querySelectorAll('#contact button')].find((b) => b.textContent.startsWith('Use my business phone')).click())
    await wait(1100)
    check((await updates(p)).slice(-1)[0].whatsapp === '+351912345678', 'back to business phone')

    await typeInto(p, 'Business phone', '91234')
    await wait(1000)
    check(await p.evaluate(() => document.body.textContent.includes('does not look like a Portugal number')), 'bad phone error')
    const before = (await updates(p)).length
    await typeInto(p, 'Business phone', '913 000 111')
    await wait(1100)
    u = await updates(p)
    check(u.length === before + 1 && u[u.length - 1].phone === '+351913000111' && u[u.length - 1].whatsapp === '+351913000111', `phone saved and WhatsApp follows ${JSON.stringify(u.slice(-1))}`)
    check(p.errors.length === 0, `errors ${p.errors}`)
    await p.close()

    p = await open('/portal/page')
    await p.evaluate(() => { window.__failNext = true })
    await typeInto(p, 'Neighbourhood', 'Anjos')
    await wait(1100)
    check(await save(p) === 'Not savedTry again', `error state ${await save(p)}`)
    await p.evaluate(() => document.querySelector('.biz-bp__retry').click())
    await wait(1100)
    check(await save(p) === 'All changes saved', 'retry saves')
    check((await updates(p)).slice(-1)[0].neighbourhood === 'Anjos', 'neighbourhood saved')
    await typeInto(p, 'Neighbourhood', 'Intendente')
    await p.evaluate(() => [...document.querySelectorAll('.biz-sidebar .biz-navlink')].find((e) => e.textContent.startsWith('Today')).click())
    await wait(800)
    check((await updates(p)).slice(-1)[0].neighbourhood === 'Intendente', 'leaving saves the last change')
    await p.close()

    p = await open('/portal/page')
    const countryBtn = await p.evaluateHandle(() => [...document.querySelectorAll('#location .ui-field')].find((f) => f.textContent.startsWith('Country')).querySelector('button'))
    await countryBtn.click(); await wait(300)
    await p.keyboard.type('Nigeria'); await wait(300); await p.keyboard.press('Enter'); await wait(1300)
    u = await updates(p)
    check(u.slice(-1)[0]?.country === 'NG' && u.slice(-1)[0].city === 'Lagos' && u.slice(-1)[0].timezone === 'Africa/Lagos', `country saved ${JSON.stringify(u.slice(-1))}`)
    check(await p.evaluate(() => document.querySelector('.biz-bp__note')?.textContent.includes('Lagos')), 'launch note shown')
    check(p.errors.length === 0, `errors ${p.errors}`)
    await p.close()

    p = await open('/portal/page#photos')
    await wait(300)
    check(await p.evaluate(() => { const r = document.getElementById('photos').getBoundingClientRect(); return r.top >= 0 && r.top < 140 }), 'hash lands on photos')
    await p.close()

    p = await open('/portal/start')
    check(await p.evaluate(() => document.querySelector('.lc-start .ui-row')?.textContent.includes('Add a logo')), 'getting started shows the open step first')
    check(await p.evaluate(() => document.querySelector('.lc-start .ui-row')?.getAttribute('href') || document.querySelector('.lc-start a.ui-row')?.getAttribute('href')) === '/portal/page#photos', 'logo step links to photos')
    await p.close()

    p = await open('/portal/page', 390, 844, true)
    check(await p.evaluate(() => !document.querySelector('.biz-bp__preview')), 'no inline preview on phone')
    await p.evaluate(() => [...document.querySelectorAll('.biz-bp__headside button')].find((b) => b.textContent.includes('Preview')).click())
    await wait(500)
    check(await p.evaluate(() => Boolean(document.querySelector('.ui-sheet .lc-pub'))), 'phone preview sheet')
    check(p.errors.length === 0, `phone errors ${p.errors}`)
    await p.close()
}
