// Formats: online sessions, and visits at the client's place by area or by distance. A service is
// offered in person, online or at the client's place; the client picks; the booking carries the rest.

import path from 'node:path'

export default async ({ browser, url, check, server, root }) => {
    const wait = (ms = 250) => new Promise((r) => setTimeout(r, ms))
    const open = async (route, extra = '', vw = 390, vh = 844) => {
        const page = await browser.newPage()
        page.errors = []
        page.on('pageerror', (e) => page.errors.push(e.message))
        await page.setViewport({ width: vw, height: vh, isMobile: vw < 1024, hasTouch: vw < 1024 })
        await page.goto(`${url}/?path=${encodeURIComponent(route)}${extra}`, { waitUntil: 'networkidle0' })
        await wait(900)
        return page
    }
    const text = (p, sel) => p.evaluate((s) => document.querySelector(s)?.textContent.trim() || '', sel)
    const click = (p, sel, label) => p.evaluate((s, l) => [...document.querySelectorAll(s)].find((b) => b.textContent.trim().includes(l))?.click(), sel, label)

    // The page says it is online, the sheet lets the client pick, the booking carries the choice.
    let p = await open('/femtos-barbearia', '&guest=1&nobiz=1&online=1')
    check(/In person or online/.test(await text(p, '.lc-pub__list')), 'the menu says a service is in person or online')
    await click(p, '.lc-pub__svc', 'Haircut')
    await wait(900)
    await p.evaluate(() => document.querySelector('.lc-bk-slot')?.click())
    await click(p, '.ui-btn, .btn', 'Continue')
    await wait(700)
    const options = await p.evaluate(() => [...document.querySelectorAll('.lc-fmt-pick .ui-seg__btn')].map((b) => b.textContent.trim()))
    check(options.length === 2 && /Online/.test(options[1]), `the client picks in person or online: ${JSON.stringify(options)}`)
    check(!/Online session/.test(await text(p, '.lc-bk-ticket')), 'in person is the first choice, with the address')
    await click(p, '.lc-fmt-pick .ui-seg__btn', 'Online')
    await wait(200)
    check(/Online session/.test(await text(p, '.lc-bk-ticket')) && !/Rua Morais Soares/.test(await text(p, '.lc-bk-ticket')), 'online: the ticket says online session and drops the address')
    const inputs = await p.$$('.lc-bk-details input')
    if (inputs[0]) await inputs[0].type('Ana Guest')
    const email = await p.$('.lc-bk-details input[type=email]')
    if (email) await email.type('ana@guest.pt')
    const phone = await p.$('.lc-bk-details input[type=tel]')
    if (phone) await phone.type('912345678')
    await wait(300)
    await click(p, '.ui-btn', 'Confirm booking')
    await wait(900)
    const sent = await p.evaluate(() => window.__calls.filter((c) => c[0] === 'rpc' && c[1] === 'book_appointment').map((c) => c[2].p_mode))
    check(sent.includes('online'), `the booking is sent as online: ${JSON.stringify(sent)}`)
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    p = await open('/femtos-barbearia', '&guest=1&nobiz=1&online=only')
    check(/Online/.test(await text(p, '.lc-pub__list')) && !/In person or online/.test(await text(p, '.lc-pub__list')), 'an online-only service says online')
    await click(p, '.lc-pub__svc', 'Haircut')
    await wait(900)
    await p.evaluate(() => document.querySelector('.lc-bk-slot')?.click())
    await click(p, '.ui-btn, .btn', 'Continue')
    await wait(700)
    check(!(await p.$('.lc-fmt-pick')) && /Online session/.test(await text(p, '.lc-bk-ticket')), 'with nothing to pick, the ticket is online')
    await p.close()

    // After booking: Join instead of Directions, and the calendar invite opens the meeting.
    p = await open('/client/appointments?booking=on1', '&onlinebooking=1')
    const card = await p.evaluate(() => {
        const el = document.getElementById('booking-on1')
        return { text: el?.textContent || '', join: el?.querySelector('a[href="https://meet.example.com/femtos"]')?.textContent.trim() || '', buttons: [...(el?.querySelectorAll('.ui-btn') || [])].map((b) => b.textContent.trim()) }
    })
    check(card.join === 'Join online', `a confirmed online booking has Join online: ${card.join}`)
    check(!card.buttons.includes('Directions') && /Online session/.test(card.text), `and no directions: ${JSON.stringify(card.buttons)}`)
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    // At the client's place: the client picks it, gives the area and address, sees the travel fee.
    p = await open('/femtos-barbearia', '&guest=1&nobiz=1&home=1')
    check(/In person or at your place/.test(await text(p, '.lc-pub__list')), 'the menu says in person or at your place')
    await click(p, '.lc-pub__svc', 'Haircut')
    await wait(900)
    await p.evaluate(() => document.querySelector('.lc-bk-slot')?.click())
    await click(p, '.ui-btn, .btn', 'Continue')
    await wait(700)
    await click(p, '.lc-fmt-pick .ui-seg__btn', 'At your place')
    await wait(300)
    const homeTicket = await text(p, '.lc-bk-ticket')
    check(/At your place/.test(homeTicket) && /Travel to you/.test(homeTicket) && /€23/.test(homeTicket), `the ticket says at your place, with the travel fee in the total: ${homeTicket}`)
    check(await p.evaluate(() => Boolean(document.querySelector('.lc-fmt-visit'))), 'and asks where to come')
    await click(p, '.ui-btn', 'Confirm booking')
    await wait(400)
    check(/Pick your area/.test(await p.evaluate(() => document.body.textContent)), 'no booking without the area and address')
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    // With address search on: the client picks the address, the area comes from it, and the distance is checked.
    p = await open('/femtos-barbearia', '&guest=1&nobiz=1&home=1&places=1&radius=1')
    await click(p, '.lc-pub__svc', 'Haircut')
    await wait(900)
    await p.evaluate(() => document.querySelector('.lc-bk-slot')?.click())
    await click(p, '.ui-btn, .btn', 'Continue')
    await wait(700)
    await click(p, '.lc-fmt-pick .ui-seg__btn', 'At your place')
    await wait(500)
    const search = await p.$('.lc-place input')
    check(Boolean(search), 'with search on, the client types the address and picks it')
    if (search) await search.type('Rua Brito')
    await wait(900)
    await p.evaluate(() => [...document.querySelectorAll('.lc-place__option')].find((o) => o.textContent.includes('Brito'))?.dispatchEvent(new MouseEvent('mousedown', { bubbles: true })))
    await wait(500)
    const reach = await text(p, '.lc-place-reach')
    check(/Rua Brito Capelo 200/.test(await text(p, '.lc-place-picked')) && /Matosinhos/.test(reach), `the picked address shows with its area: ${reach}`)
    check(/Matosinhos/.test(await text(p, '.lc-bk-ticket')), 'the ticket takes the area from the address')
    const unit = await p.$('.lc-fmt-visit input[autocomplete="address-line2"]')
    if (unit) await unit.type('2 Esq')
    const homeInputs = await p.$$('.lc-bk-details input')
    if (homeInputs[0]) await homeInputs[0].type('Ana Guest')
    const homeEmail = await p.$('.lc-bk-details input[type=email]')
    if (homeEmail) await homeEmail.type('ana@guest.pt')
    const homePhone = await p.$('.lc-bk-details input[type=tel]')
    if (homePhone) await homePhone.type('912345678')
    await wait(300)
    await click(p, '.ui-btn', 'Confirm booking')
    await wait(900)
    const homeSent = await p.evaluate(() => window.__calls.filter((c) => c[0] === 'rpc' && c[1] === 'book_appointment').map((c) => c[2]).pop() || {})
    check(homeSent.p_client_zone === 'Matosinhos' && homeSent.p_client_place_id === 'ChIJnear00000001' && Math.abs(homeSent.p_client_lat - 41.1821) < 0.001, `the booking carries the area, the place and the spot: ${JSON.stringify({ z: homeSent.p_client_zone, id: homeSent.p_client_place_id })}`)
    check(homeSent.p_client_address === 'Rua Brito Capelo 200, 2 Esq, 4450-073 Matosinhos', `floor and door go after the street: ${homeSent.p_client_address}`)
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    p = await open('/femtos-barbearia', '&guest=1&nobiz=1&home=1&places=1&radius=1')
    await click(p, '.lc-pub__svc', 'Haircut')
    await wait(900)
    await p.evaluate(() => document.querySelector('.lc-bk-slot')?.click())
    await click(p, '.ui-btn, .btn', 'Continue')
    await wait(700)
    await click(p, '.lc-fmt-pick .ui-seg__btn', 'At your place')
    await wait(500)
    const farSearch = await p.$('.lc-place input')
    if (farSearch) await farSearch.type('Rua de Camilo')
    await wait(900)
    await p.evaluate(() => [...document.querySelectorAll('.lc-place__option')].find((o) => o.textContent.includes('Camilo'))?.dispatchEvent(new MouseEvent('mousedown', { bubbles: true })))
    await wait(500)
    check(await p.evaluate(() => Boolean(document.querySelector('.lc-place-reach.is-out'))) && /24\.2 km/.test(await text(p, '.lc-place-reach')), 'too far: the client sees how far, before booking')
    await click(p, '.ui-btn', 'Confirm booking')
    await wait(400)
    check(!(await p.evaluate(() => window.__calls.some((c) => c[0] === 'rpc' && c[1] === 'book_appointment'))), 'and cannot book it')
    await p.close()

    p = await open('/portal/services', '&home=1&places=1&radius=1')
    const reachText = await p.evaluate(() => document.querySelector('.biz-reach')?.textContent || '')
    check(/Or by distance from your shop/.test(reachText) && /up to 10 km away/.test(reachText), `Services sets how far the business travels from its shop: ${reachText.slice(0, 120)}`)
    check(await p.evaluate(() => [...document.querySelectorAll('.biz-reach .ui-chip.is-selected')].map((c) => c.textContent.trim()).join() === '10 km'), 'the distance is a choice of chips')
    await p.close()

    // On the way: the client sees minutes and steps, never a place.
    p = await open('/client/appointments?booking=hm2', '&trip=1')
    const tripText = await p.evaluate(() => document.querySelector('#booking-hm2 .lc-trip')?.textContent || '')
    check(/is on the way/.test(tripText) && /About 1[12] min/.test(tripText) && /Arriving around \d{2}:\d{2}/.test(tripText), `the client follows the minutes: ${tripText.slice(0, 120)}`)
    check(/never where they are/.test(tripText) && !/\d+\.\d{3,}/.test(tripText), 'and only minutes, never a position')
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    // The business: On my way, minutes picked by hand when location is off, then Arrived.
    p = await open('/portal/calendar?booking=tr1', '&trip=1')
    await p.evaluate(() => { navigator.geolocation.getCurrentPosition = (ok, fail) => fail({ code: 1 }) })
    check(/On my way/.test(await text(p, '.biz-trip')), 'a visit at the client\'s place today offers On my way')
    await click(p, '.biz-trip .ui-btn', 'On my way')
    await wait(600)
    await click(p, '.biz-trip .ui-chip', '15 min')
    await wait(600)
    check(/The client sees about 1[45] min/.test(await text(p, '.biz-trip')), `with location off, the business picks the minutes: ${await text(p, '.biz-trip')}`)
    await click(p, '.biz-trip .ui-btn', 'Arrived')
    await wait(600)
    check(/Arrived at \d{2}:\d{2}\. The client was told\./.test(await text(p, '.biz-trip__done')), 'Arrived ends the trip and tells the client')
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    p = await open('/client/appointments?booking=hm1', '&homebooking=1')
    const homeCard = await p.evaluate(() => {
        const el = document.getElementById('booking-hm1')
        return { text: el?.textContent || '', buttons: [...(el?.querySelectorAll('.ui-btn') || [])].map((b) => b.textContent.trim()) }
    })
    check(/comes to Rua das Flores 12, Matosinhos/.test(homeCard.text) && !homeCard.buttons.includes('Directions'), `a home visit says where the business comes, with no directions: ${homeCard.text.slice(0, 160)}`)
    await p.close()

    p = await open('/portal/services', '&home=1')
    check(await p.evaluate(() => /Where you go/.test(document.body.textContent)), 'Services asks where the business travels once a service is at the client\'s place')
    await p.close()

    // Groups: the client says how many people; time and price follow; the booking carries it.
    p = await open('/femtos-barbearia', '&guest=1&nobiz=1&group=1')
    check(/Up to 4 people, priced per person/.test(await text(p, '.lc-pub__list')), 'the menu says the service takes groups and how it is priced')
    await click(p, '.lc-pub__svc', 'Haircut')
    await wait(900)
    const sizes = await p.evaluate(() => [...document.querySelectorAll('.lc-bk-people .ui-chip')].map((c) => c.textContent.trim()))
    check(JSON.stringify(sizes) === JSON.stringify(['Just me', '2', '3', '4']), `the client picks how many people: ${JSON.stringify(sizes)}`)
    await click(p, '.lc-bk-people .ui-chip', '3')
    await wait(700)
    check(/1 h 30 min in all, priced per person/.test(await text(p, '.lc-bk-people__note')), `three people take three times as long: ${await text(p, '.lc-bk-people__note')}`)
    check(/Haircut for 3 people/.test(await text(p, '.lc-bk-service')) && /54/.test(await text(p, '.lc-bk-service')), `the service line says three people and three prices: ${await text(p, '.lc-bk-service')}`)
    check(await p.evaluate(() => window.__calls.some((c) => c[0] === 'rpc' && c[1] === 'get_available_slots' && c[2].p_people === 3)), 'free times are asked for the whole group')
    check(!(await p.$('.lc-bk-extras:not(.lc-bk-people)')), 'extras are not offered to a group')
    await p.evaluate(() => document.querySelector('.lc-bk-slot')?.click())
    await click(p, '.ui-btn, .btn', 'Continue')
    await wait(700)
    const groupInputs = await p.$$('.lc-bk-details input')
    if (groupInputs[0]) await groupInputs[0].type('Ana Guest')
    const groupEmail = await p.$('.lc-bk-details input[type=email]')
    if (groupEmail) await groupEmail.type('ana@guest.pt')
    const groupPhone = await p.$('.lc-bk-details input[type=tel]')
    if (groupPhone) await groupPhone.type('912345678')
    await wait(300)
    await click(p, '.ui-btn', 'Confirm booking')
    await wait(900)
    const groupSent = await p.evaluate(() => window.__calls.filter((c) => c[0] === 'rpc' && c[1] === 'book_appointment').map((c) => c[2]).pop() || {})
    check(groupSent.p_people === 3 && groupSent.p_addon_ids === null, `the booking is for three people and no extras: ${groupSent.p_people}`)
    check(p.errors.length === 0, `no page errors: ${p.errors.join(' | ')}`)
    await p.close()

    p = await open('/portal/services', '&group=1')
    check(/Up to 4 people/.test(await text(p, '.biz-svc')), 'Services lists the service as taking groups')
    await p.close()

    // The business sets one meeting link for every online session.
    p = await open('/portal/services', '&online=1')
    check(await p.evaluate(() => Boolean(document.querySelector('.biz-sh__meet input'))), 'Services asks for the meeting link once a service is online')
    await p.close()

    // The time on the client's own clock.
    const formats = await server.ssrLoadModule(path.join(root, 'src', 'services', 'formats.js'))
    check(formats.yourTime({ dateKey: '2026-10-09', minutes: 600, timeZone: 'Europe/Lisbon' }, 'Africa/Lagos') === null, 'Lisbon and Lagos share a clock in October, so nothing to say')
    check(formats.yourTime({ dateKey: '2027-01-15', minutes: 600, timeZone: 'Europe/Lisbon' }, 'Africa/Lagos') === '11:00 your time', 'in winter Lagos is an hour ahead of Lisbon')
    check(formats.yourTime({ dateKey: '2026-10-09', minutes: 1410, timeZone: 'Europe/Lisbon' }, 'Asia/Tokyo') === '07:30 your time, Sat 10 Oct', 'a late session can be the next day for the client')
    check(formats.yourTime({ dateKey: '2026-10-09', minutes: 600, timeZone: 'Europe/Lisbon' }, 'Europe/Berlin') === '11:00 your time', 'Berlin is an hour ahead')
    check(formats.yourTime({ dateKey: '2026-10-09', minutes: 600, timeZone: 'Europe/Lisbon' }, 'Europe/Lisbon') === null, 'same clock, nothing to say')
    check(/^05:00 your time/.test(formats.yourTime({ dateKey: '2026-10-09', minutes: 600, timeZone: 'Europe/Lisbon' }, 'America/New_York') || ''), 'New York is five hours behind')
    check(formats.joinLink({ mode: 'online', status: 'pending', meeting_url: 'https://x.y/z' }) === null && formats.joinLink({ mode: 'online', status: 'confirmed', meeting_url: 'https://x.y/z' }) === 'https://x.y/z', 'the link only once confirmed')
}
