export default async ({ browser, url, check }) => {
    const wait = (ms = 250) => new Promise((r) => setTimeout(r, ms))
    const open = async (path, vw = 1272, vh = 588, touch = false) => {
      const page = await browser.newPage()
      page.errors = []
      page.on('pageerror', (e) => page.errors.push(e.message))
      await page.setViewport({ width: vw, height: vh, hasTouch: touch, isMobile: touch })
      await page.goto(`${url}/?path=${encodeURIComponent(path.split('&')[0])}${path.includes('&') ? '&' + path.split('&').slice(1).join('&') : ''}`, { waitUntil: 'networkidle0' })
      await wait(500)
      return page
    }
    const calls = (p, table, kind) => p.evaluate((table, kind) => window.__calls.filter((c) => c[1] === table && c[0] === kind).map((c) => c[2]), table, kind)
    const text = (p, sel) => p.evaluate((sel) => document.querySelector(sel)?.textContent.trim(), sel)
    const clickText = (p, sel, t) => p.evaluate((sel, t) => { const el = [...document.querySelectorAll(sel)].find((e) => e.textContent.trim().startsWith(t)); if (el) el.click(); return Boolean(el) }, sel, t)
    const selectAll = async (p) => { await p.keyboard.down('Control'); await p.keyboard.press('a'); await p.keyboard.up('Control') }
    const rowNames = (p) => p.evaluate(() => [...document.querySelectorAll('.biz-svc__item')].map((li) => li.querySelector('.biz-svc__name, input')?.textContent || li.querySelector('input')?.value))

    let p = await open('/portal/services')
    await wait(1200)
    check((await calls(p, 'services', 'update')).length === 0 && (await calls(p, 'services', 'insert')).length === 0, 'no save on open')
    check(await p.evaluate(() => document.querySelectorAll('.biz-svc__item .biz-svc__dial').length) === 2, 'every service shows its duration dial')
    check(await text(p, '.biz-page__sub') === '2 services on your page, from €12.', `summary ${await text(p, '.biz-page__sub')}`)
    check(await text(p, '.biz-save') === 'Changes save as you go', 'idle state')

    await clickText(p, '.biz-svc__open', 'Haircut')
    await wait(300)
    check(await p.evaluate(() => Boolean(document.querySelector('.biz-svc__item.is-open .ui-switchrow'))), 'visibility switch in the form')
    const price = await p.evaluateHandle(() => document.querySelector('.biz-svc__item.is-open .ui-affix input'))
    await price.focus(); await selectAll(p); await p.keyboard.type('20')
    await wait(1400)
    let up = await calls(p, 'services', 'update')
    check(up.some((u) => u.price === 20 && u.service_name === 'Haircut'), `price saved ${JSON.stringify(up.slice(-2))}`)
    check(await text(p, '.biz-save') === 'All changes saved', 'saved state')
    check(await text(p, '.biz-page__sub') === '2 services on your page, from €12.', 'summary still right')
    await clickText(p, '.biz-svc__formactions button', 'Done')

    await clickText(p, '.biz-svc__suggest .ui-chip', 'Skin fade')
    await wait(300)
    check(await p.evaluate(() => document.activeElement.closest('.ui-affix') !== null), 'suggestion opens with price focused')
    await wait(2000)
    check(await text(p, '.biz-save') === 'Finish the highlighted service to save it', `blocked ${await text(p, '.biz-save')}`)
    check(await p.evaluate(() => document.body.textContent.includes('Enter a price, or 0 if it is free')), 'price error shown')
    check((await calls(p, 'services', 'insert')).length === 0, 'nothing inserted while incomplete')
    await p.keyboard.type('22')
    await wait(1500)
    const ins = await calls(p, 'services', 'insert')
    check(ins.length === 1 && ins[0].service_name === 'Skin fade' && ins[0].price === 22 && ins[0].duration_minutes === 45 && ins[0].business_id === 'b1', `insert ${JSON.stringify(ins)}`)
    check(await text(p, '.biz-page__sub') === '3 services on your page, from €12.', 'summary counts three')
    await wait(1200)
    const before = (await calls(p, 'services', 'update')).length + (await calls(p, 'services', 'insert')).length
    await wait(1500)
    check((await calls(p, 'services', 'update')).length + (await calls(p, 'services', 'insert')).length === before, 'no repeat saves once saved')
    await clickText(p, '.biz-svc__formactions button', 'Done')
    await wait(300)

    await p.evaluate(() => document.querySelector('[aria-label^="Reorder Beard trim"]').focus())
    await p.keyboard.press('ArrowUp')
    await wait(1500)
    up = await calls(p, 'services', 'update')
    const last3 = up.slice(-3)
    check(last3.find((u) => u.service_name === 'Beard trim')?.sort_order === 0 && last3.find((u) => u.service_name === 'Haircut')?.sort_order === 1, `reorder saved ${JSON.stringify(last3.map((u) => [u.service_name, u.sort_order]))}`)

    await clickText(p, '.biz-svc__open', 'Beard trim')
    await wait(300)
    await clickText(p, '.biz-svc__formactions button', 'Remove')
    await wait(600)
    check(await text(p, '.ui-sheet h2, .ui-sheet [id]') !== undefined, 'sheet opens')
    check(await p.evaluate(() => document.body.textContent.includes('Beard trim has 1 booking')), 'booked service warns')
    check((await calls(p, 'services', 'delete')).length === 0, 'booked service not deleted')
    await clickText(p, '.ui-sheet button', 'Hide from your page')
    await wait(1500)
    up = await calls(p, 'services', 'update')
    check(up.some((u) => u.service_name === 'Beard trim' && u.is_active === false), 'hidden saved')
    check(await p.evaluate(() => [...document.querySelectorAll('.biz-svc__item.is-open .ui-switchrow')].find((r) => r.textContent.includes('Show on your page'))?.querySelector('[role=switch]').getAttribute('aria-checked')) === 'false', 'switch shows hidden')
    await clickText(p, '.biz-svc__formactions button', 'Done')
    await wait(300)
    check(await p.evaluate(() => document.querySelector('.biz-svc__item.is-hidden .biz-svc__hidden')?.textContent === 'Hidden'), 'hidden label on the row')
    check(await text(p, '.biz-page__sub') === '2 services on your page, from €20. 1 hidden.', `summary with hidden ${await text(p, '.biz-page__sub')}`)

    await clickText(p, '.biz-svc__open', 'Skin fade')
    await wait(300)
    await clickText(p, '.biz-svc__formactions button', 'Remove')
    await wait(600)
    check(await p.evaluate(() => document.body.textContent.includes('Remove Skin fade?')), 'unbooked service asks to remove')
    await clickText(p, '.ui-sheet button', 'Remove service')
    await wait(1500)
    const del = await p.evaluate(() => window.__calls.filter((c) => c[0] === 'deleted' && c[1] === 'services').map((c) => c[2]))
    check(del.length === 1 && del[0].length === 1 && del[0][0].startsWith('services-'), `only Skin fade deleted ${JSON.stringify(del)}`)
    check(!(await rowNames(p)).some((n) => n === 'Skin fade'), 'row gone')

    await clickText(p, '.biz-svc__open', 'Haircut')
    await wait(300)
    await p.evaluate(() => [...document.querySelectorAll('.biz-svc__item.is-open .ui-switchrow')].find((r) => r.textContent.includes('Show on your page'))?.querySelector('[role=switch]').click())
    await wait(400)
    check(await p.evaluate(() => document.body.textContent.includes('Keep at least one service')), 'last visible service is protected')
    await clickText(p, '.ui-sheet button', 'Cancel')
    await wait(300)
    check(await p.evaluate(() => [...document.querySelectorAll('.biz-svc__item.is-open .ui-switchrow')].find((r) => r.textContent.includes('Show on your page'))?.querySelector('[role=switch]').getAttribute('aria-checked')) === 'true', 'switch stays on')
    check(p.errors.length === 0, `errors ${p.errors}`)
    await p.close()

    p = await open('/portal/services')
    await p.evaluate(() => { window.__failNext = true })
    await clickText(p, '.biz-svc__open', 'Haircut')
    await wait(300)
    const price2 = await p.evaluateHandle(() => document.querySelector('.biz-svc__item.is-open .ui-affix input'))
    await price2.focus(); await selectAll(p); await p.keyboard.type('19')
    await wait(1500)
    check((await text(p, '.biz-save')).startsWith('Not saved'), `error state ${await text(p, '.biz-save')}`)
    await p.evaluate(() => document.querySelector('.biz-save__retry').click())
    await wait(1500)
    check(await text(p, '.biz-save') === 'All changes saved', 'retry saves')
    await price2.focus(); await selectAll(p); await p.keyboard.type('21')
    await p.evaluate(() => [...document.querySelectorAll('.biz-hubnav__tab')].find((e) => e.textContent === 'Hours').click())
    await wait(900)
    check((await calls(p, 'services', 'update')).some((u) => u.price === 21), 'leaving saves the last change')
    await p.close()

    p = await open('/portal/hours&nohours=1')
    await wait(1200)
    check((await calls(p, 'availability', 'insert')).length === 0 && (await calls(p, 'availability', 'update')).length === 0, 'hours: no save on open')
    check(await p.evaluate(() => !document.querySelector('.biz-wk__state')), 'empty week has no status')
    check(await p.evaluate(() => document.querySelectorAll('.biz-sched__template').length) === 3, 'templates offered for an empty week')
    check(await p.evaluate(() => Boolean(document.querySelector('.biz-wk--empty .biz-sign'))), 'empty week shows the blank door sign')
    check(await p.evaluate(() => document.body.textContent.includes('Pick the days you open') && !document.querySelector('.biz-sched__card.has-error')), 'empty week is a hint, not an error')
    await clickText(p, '.biz-sched__template', 'Tuesday to Saturday')
    await wait(1600)
    const state = await p.evaluate(() => window.__calls.filter((c) => c[1] === 'availability' && c[0] !== 'from').map((c) => c[0]))
    check(state.includes('insert'), `hours saved ${state}`)
    check(/^(Open now|Closed now)$/.test(await text(p, '.biz-wk__state')) && Boolean(await text(p, '.biz-wk__next')), `status line ${await text(p, '.biz-wk__state')}`)
    check(await p.evaluate(() => document.querySelectorAll('.biz-wk__bar').length) === 10, 'week view draws lunch as a gap')
    check(await p.evaluate(() => [...document.querySelectorAll('.biz-wk__lunch')].filter((e) => e.textContent === 'Lunch 14:00 to 15:00').length) === 5, 'lunch written under each day')
    check(await p.evaluate(() => document.querySelectorAll('.biz-wk__row.is-today').length) === 1, 'today marked once')
    check(await text(p, '.biz-save') === 'All changes saved', 'hours saved state')
    check(await p.evaluate(() => document.querySelector('.biz-sched > p.ui-visually-hidden').textContent) === 'Tuesday to Saturday, 10:00 to 19:00, lunch 14:00 to 15:00. Closed Monday and Sunday.', 'summary sentence')
    await clickText(p, '.biz-sched button', 'Different hours on other days')
    await wait(1600)
    check(await p.evaluate(() => document.querySelectorAll('.biz-sched__card').length) === 2, 'second group added')
    check(await p.evaluate(() => document.querySelector('.biz-sched > p.ui-visually-hidden').textContent.includes('Monday, 10:00 to 16:00')), 'monday added')
    await clickText(p, '.biz-sched__foot button', 'Remove these days')
    await wait(1600)
    check(await p.evaluate(() => document.querySelectorAll('.biz-sched__card').length) === 1, 'group removed')
    const days = await p.evaluate(() => [...document.querySelectorAll('.biz-sched__day[aria-pressed="true"]')].map((b) => b.getAttribute('aria-label')))
    for (const d of days) await p.evaluate((d) => document.querySelector(`.biz-sched__day[aria-label="${d}"]`).click(), d)
    await wait(1500)
    check(await text(p, '.biz-save') === 'Open at least one day to save your hours', `hours blocked ${await text(p, '.biz-save')}`)
    check(await p.evaluate(() => document.body.textContent.includes('Pick the days you open')), 'day hint shown')
    const saves = (await calls(p, 'availability', 'delete')).length
    await wait(1200)
    check((await calls(p, 'availability', 'delete')).length === saves, 'closed week never saved')
    await p.evaluate(() => document.querySelector('.biz-sched__day[aria-label="Wednesday"]').click())
    await wait(1500)
    check(await text(p, '.biz-save') === 'All changes saved', 'saves again once valid')
    check(p.errors.length === 0, `hours errors ${p.errors}`)
    await p.close()

    p = await open('/portal/hours', 390, 844, true)
    const fit = await p.evaluate(() => {
      const days = [...document.querySelectorAll('.biz-sched__day')].map((b) => b.getBoundingClientRect())
      const row = new Set(days.map((r) => Math.round(r.top)))
      return { rows: row.size, min: Math.min(...days.map((r) => r.width)) }
    })
    check(fit.rows === 1, `seven days on one row ${JSON.stringify(fit)}`)
    check(fit.min >= 40, `day buttons large enough ${JSON.stringify(fit)}`)
    check(p.errors.length === 0, `phone errors ${p.errors}`)
    await p.close()
}
